# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false


format = """
$directory$git_branch$git_status$character
"""

right_format = """
${env_var.NIX_DEV_SHELL} $shell
"""

[character]
success_symbol = "[ î©± ï‹](bold fg:blue)"
error_symbol = "[ ï€ ï‹](bold fg:red)"

[shell]
fish_indicator = 'ó°ˆº '
unknown_indicator = 'ï‘ _'
nu_indicator = 'îš‘'
format = "[$indicator](bold fg:#1e1e2e) "
disabled = false

[directory]
home_symbol = "ï‘­ "
read_only = "ï‘– "
truncation_length = 20
truncation_symbol = "â€¢â€¢/"
format = '[$path](bold fg:green)'

[directory.substitutions]
"Desktop" = "ï’© "
"Documents" = "ï’¥ "
"Downloads" = "ï‰ "
"Music" = "ó°ˆ "
"Pictures" = "ï "
"Videos" = "ï”¬ "
"GitHub" = "ó°Š¤ "

[username]
style_user = "bold fg:black"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[@$hostname](bold fg:black)"
disabled = false

[git_branch]
style = "bg: cyan"
symbol = "ó°˜¬"
truncation_length = 12
truncation_symbol = ""
format = " [$symbol $branch(:$remote_branch)](fg:#b4befe)"

[git_status]
conflicted = 'ğŸ³'
ahead = ' â‡¡${count}'
diverged = ' â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = ' â‡£${count}'
up_to_date = ''
untracked = ' î¬² ${count}'
stashed = ' ï” '
modified = ' î« ${count}'
staged = ' ïƒ¾ ${count}'
renamed = ' ï€Ÿ '
deleted = ' î¸£ '
format = '[$untracked](fg:red)[$modified](fg:yellow)[$staged](fg:green)[$ahead_behind](fg:#f5c2e7)'


[cmd_duration]
min_time = 0
format = '[ó°ª¢ $duration](bold fg:#cdd6f4)'

[env_var.NIX_DEV_SHELL]
variable = "NIX_DEV_SHELL"
format = '[î• $env_value](bold fg:#cdd6f4)'

[package]
disabled = true
